# Auto generated by update-sources.sh
{
  xlibre = {
    # xserver
    xserver = {
      version = "25.1.0";
      url = "https://github.com/X11Libre/xserver/archive/refs/tags/xlibre-xserver-25.1.0.tar.gz";
      sha256 = "sha256-tG/oXjBoIVBKXg6Rqg2NVM5937ZxBsSVpspawsPijwY=";
    };

    # drivers
    xf86-input-elographics = {
      version = "25.0.1";
      url = "https://github.com/X11Libre/xf86-input-elographics/archive/refs/tags/xlibre-xf86-input-elographics-25.0.1.tar.gz";
      sha256 = "sha256-DCqCiBGZoI7GI24TOPdpnqQtgsrS+vyZ6YaWROgkDps=";
    };
    xf86-input-evdev = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-evdev/archive/refs/tags/xlibre-xf86-input-evdev-25.0.0.tar.gz";
      sha256 = "sha256-yBDMLUumPukX9AsS6OCcPgRmU7rcqs5ol1Yd0wh5ROg=";
    };
    xf86-input-joystick = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-joystick/archive/refs/tags/xlibre-xf86-input-joystick-25.0.0.tar.gz";
      sha256 = "sha256-r4IeEUd9jBvbCO4sut/VVhWdQrOUaZssmAqlyBhEFSA=";
    };
    xf86-input-keyboard = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-keyboard/archive/refs/tags/xlibre-xf86-input-keyboard-25.0.0.tar.gz";
      sha256 = "sha256-K8bYEJDOMFZF0kckJS6FEOgyzyUtThxT7Phv+M97204=";
    };
    xf86-input-libinput = {
      version = "25.0.1";
      url = "https://github.com/X11Libre/xf86-input-libinput/archive/refs/tags/xlibre-xf86-input-libinput-25.0.1.tar.gz";
      sha256 = "sha256-19kka2+aA0WaW2A7cmqk5MDsjqZp//LziXa8ge7JakQ=";
    };
    xf86-input-mouse = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-mouse/archive/refs/tags/xlibre-xf86-input-mouse-25.0.0.tar.gz";
      sha256 = "sha256-zexi8lbQ40OwyAy6eKAW8sZQc/4gc/13GiIENuOqZps=";
    };
    xf86-input-synaptics = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-synaptics/archive/refs/tags/xlibre-xf86-input-synaptics-25.0.0.tar.gz";
      sha256 = "sha256-/KahbtGZUFon3BZ+iHIrTUWqX0boZWHWxu7j16dQoQc=";
    };
    xf86-input-vmmouse = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-vmmouse/archive/refs/tags/xlibre-xf86-input-vmmouse-25.0.0.tar.gz";
      sha256 = "sha256-Qcdg1UeYnQsSC3bimcKyYR8T+wY4OPtsP6f+Jut1b74=";
    };
    xf86-input-void = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-void/archive/refs/tags/xlibre-xf86-input-void-25.0.0.tar.gz";
      sha256 = "sha256-KyQrVeQpwl4xyohN7fQ7tgvk290Kf/AV8Q+iPNbggGQ=";
    };
    xf86-input-wacom = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-input-wacom/archive/refs/tags/xlibre-xf86-input-wacom-25.0.0.tar.gz";
      sha256 = "sha256-EoeFR7Jx9OWezVCY+TXUwL1FYNDCo6ZnOF2Ra8Y9AK8=";
    };
    xf86-video-amdgpu = {
      version = "25.1.1";
      url = "https://github.com/X11Libre/xf86-video-amdgpu/archive/refs/tags/xlibre-xf86-video-amdgpu-25.1.1.tar.gz";
      sha256 = "sha256-NF66PXAbDdO+JAA47owFxzBvGfZDwr2NCCMnUoYqwmQ=";
    };
    xf86-video-ast = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-ast/archive/refs/tags/xlibre-xf86-video-ast-25.0.0.tar.gz";
      sha256 = "sha256-zrBz+52ss1IU8qAIzIMXVFrvkClGFUJB+NUCZNzTIpM=";
    };
    xf86-video-ati = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-ati/archive/refs/tags/xlibre-xf86-video-ati-25.0.0.tar.gz";
      sha256 = "sha256-WX6bP5sbT15A/W0XBvT/5tMbvClV1PQ10eMBTy4Im94=";
    };
    xf86-video-dummy = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-dummy/archive/refs/tags/xlibre-xf86-video-dummy-25.0.0.tar.gz";
      sha256 = "sha256-tW5hBwXNPU2GQioRxrDZM1fk1HSaBReKhf0lAwHTV7k=";
    };
    xf86-video-fbdev = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-fbdev/archive/refs/tags/xlibre-xf86-video-fbdev-25.0.0.tar.gz";
      sha256 = "sha256-Y4/9uy5DqaK3aIPv3mRacSP/NIISt3Iv6XDjlJ77mAg=";
    };
    xf86-video-geode = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-geode/archive/refs/tags/xlibre-xf86-video-geode-25.0.0.tar.gz";
      sha256 = "sha256-hgaWpz7fC7F/CoI/m30rjUE5/9GbRxrqFwhIkVXJ0HI=";
    };
    xf86-video-intel = {
      version = "25.0.1";
      url = "https://github.com/X11Libre/xf86-video-intel/archive/refs/tags/xlibre-xf86-video-intel-25.0.1.tar.gz";
      sha256 = "sha256-m2/4QaepIdzKULP24B6E+rT/unFne4P46C0QaVv1n10=";
    };
    xf86-video-mga = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-mga/archive/refs/tags/xlibre-xf86-video-mga-25.0.0.tar.gz";
      sha256 = "sha256-r2GaNua3yPlR48EymIm7rNiGTtjeoy0warjP10iyStQ=";
    };
    xf86-video-nouveau = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-nouveau/archive/refs/tags/xlibre-xf86-video-nouveau-25.0.0.tar.gz";
      sha256 = "sha256-vFbzILps5NBoNRrCWc24dXGgXgNAKvrQI1K8tivnsEA=";
    };
    xf86-video-nv = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-nv/archive/refs/tags/xlibre-xf86-video-nv-25.0.0.tar.gz";
      sha256 = "sha256-zIVz+zZyQQUjtrl1jyr/sfCGe/lXCMCSJ54OMBTxKwQ=";
    };
    xf86-video-qxl = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-qxl/archive/refs/tags/xlibre-xf86-video-qxl-25.0.0.tar.gz";
      sha256 = "sha256-7gsHmKL6LdPiSU3umWzcQawuQwVPU7M6YZlgeG1bfow=";
    };
    xf86-video-r128 = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-r128/archive/refs/tags/xlibre-xf86-video-r128-25.0.0.tar.gz";
      sha256 = "sha256-W47qcRs+4Sr/Z0AbsafQVGvIwUZlcZmKR+7VwbnBVOs=";
    };
    xf86-video-siliconmotion = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-siliconmotion/archive/refs/tags/xlibre-xf86-video-siliconmotion-25.0.0.tar.gz";
      sha256 = "sha256-VqI4fVGN+YrIWgAvPCnqgMw9JXgC1kRQY+wc54dlWiQ=";
    };
    xf86-video-vesa = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-vesa/archive/refs/tags/xlibre-xf86-video-vesa-25.0.0.tar.gz";
      sha256 = "sha256-jVF8vZOkKyAs9iTo9WtkaqXvrNROAB+An+psXAj43+c=";
    };
    xf86-video-vmware = {
      version = "25.0.0";
      url = "https://github.com/X11Libre/xf86-video-vmware/archive/refs/tags/xlibre-xf86-video-vmware-25.0.0.tar.gz";
      sha256 = "sha256-Wqv1ky/gccIfYhpb+lvJNSPL1u8QzvXz7Pib8Opmu7Q=";
    };
  };

  # This part is for legacy drivers (from tags before it become xlibre)
  # This will only be used when the attribute in the flake input of "./consumer-overridable/drivers-overlay-choice.nix" is override to false
  # Further usage, see README.md
  #
  # Don't touch below settings.
  legacy = {
    xf86-input-elographics = rec {
      version = "1.4.4";
      url = "https://github.com/X11Libre/xf86-input-elographics/archive/refs/tags/xf86-input-elographics-${version}.tar.gz";
      sha256 = "sha256-u2AJQ/sFPBHqtyLgbOQrX9Qigs7yJsCcIpGSQfOgKBc=";
    };
    xf86-input-evdev = rec {
      version = "2.11.0";
      url = "https://github.com/X11Libre/xf86-input-evdev/archive/refs/tags/xf86-input-evdev-${version}.tar.gz";
      sha256 = "sha256-u8PyA/5WDtKxjlPZTMRsKaGY/Sw+ME8lmAzaC+7exRw=";
    };
    xf86-input-joystick = rec {
      version = "1.6.4";
      url = "https://github.com/X11Libre/xf86-input-joystick/archive/refs/tags/xf86-input-joystick-${version}.tar.gz";
      sha256 = "sha256-WyPr0dt6sELIxJxUlhGs4nMjk3g0hPW7xcNL6Ubo69s=";
    };
    xf86-input-keyboard = rec {
      version = "2.1.0";
      url = "https://github.com/X11Libre/xf86-input-keyboard/archive/refs/tags/xf86-input-keyboard-${version}.tar.gz";
      sha256 = "sha256-rWHZyoUx6UvLlUY91oSwZ/YtfuYKqTnPz7rBlIH1Ziw=";
    };
    xf86-input-libinput = rec {
      version = "1.5.0";
      url = "https://github.com/X11Libre/xf86-input-libinput/archive/refs/tags/xf86-input-libinput-${version}.tar.gz";
      sha256 = "sha256-zLTtQLRMm5kdXeon+L71iq000Vv1kIR7SP79WYLH1Fw=";
    };
    xf86-input-mouse = rec {
      version = "1.9.5";
      url = "https://github.com/X11Libre/xf86-input-mouse/archive/refs/tags/xf86-input-mouse-${version}.tar.gz";
      sha256 = "sha256-wdoX+pM/ErfU1dQDvaCzt8GR3FsjbmWU68vRJltrdKg=";
    };
    xf86-input-synaptics = rec {
      version = "1.10.0";
      url = "https://github.com/X11Libre/xf86-input-synaptics/archive/refs/tags/xf86-input-synaptics-${version}.tar.gz";
      sha256 = "sha256-st/P+3qvraeb/Sjcz7seJf+ToVAMy0tx6ZW4+81RH+g=";
    };
    xf86-input-vmmouse = rec {
      version = "13.2.0";
      url = "https://github.com/X11Libre/xf86-input-vmmouse/archive/refs/tags/xf86-input-vmmouse-${version}.tar.gz";
      sha256 = "sha256-LP66258u5w5SwHNXluJjvRD+ylE26AJEEUw0HtPCJX8=";
    };
    xf86-input-void = rec {
      version = "1.4.2";
      url = "https://github.com/X11Libre/xf86-input-void/archive/refs/tags/xf86-input-void-${version}.tar.gz";
      sha256 = "sha256-5fa8eW1hmds9HNKu5tnyaSOJdxgL0NNMLjv6JGZUfeY=";
    };
    xf86-input-wacom = rec {
      version = "1.2.3";
      url = "https://github.com/X11Libre/xf86-input-wacom/archive/refs/tags/xf86-input-wacom-${version}.tar.gz";
      sha256 = "sha256-hfBsUwQXpT83lJbRAbAFxH1721XSN0zqTE6OzfTdHus=";
    };
    xf86-video-amdgpu = rec {
      version = "23.0.0";
      url = "https://github.com/X11Libre/xf86-video-amdgpu/archive/refs/tags/xf86-video-amdgpu-${version}.tar.gz";
      sha256 = "sha256-9ZPadeSfW8b1AGavA5Q7YiyAe5uHkcZUX00cYGb6FfE=";
    };
    xf86-video-ast = rec {
      version = "1.2.0";
      url = "https://github.com/X11Libre/xf86-video-ast/archive/refs/tags/xf86-video-ast-${version}.tar.gz";
      sha256 = "sha256-8ttga6ZC22Q5uFJPp7BwHqBy1ZlLzU5BHHTTiA/X40k=";
    };
    xf86-video-ati = rec {
      version = "22.0.0";
      url = "https://github.com/X11Libre/xf86-video-ati/archive/refs/tags/xf86-video-ati-${version}.tar.gz";
      sha256 = "sha256-Ot26i+eR0JKdecATg3SPUg7EgdgNfKtnBXQak3Z22YY=";
    };
    xf86-video-dummy = rec {
      version = "0.4.1";
      url = "https://github.com/X11Libre/xf86-video-dummy/archive/refs/tags/xf86-video-dummy-${version}.tar.gz";
      sha256 = "sha256-P1ydmQSw5Wg+3VRtfeKWAEXbybXjAdq9OrujwvH3G+o=";
    };
    xf86-video-fbdev = rec {
      version = "0.5.1";
      url = "https://github.com/X11Libre/xf86-video-fbdev/archive/refs/tags/xf86-video-fbdev-${version}.tar.gz";
      sha256 = "sha256-aZ+TjHq//OFna481IM8BI08qX8Kzr37l0I5JgKgES0s=";
    };
    xf86-video-geode = rec {
      version = "2.18.1";
      url = "https://github.com/X11Libre/xf86-video-geode/archive/refs/tags/xf86-video-geode-${version}.tar.gz";
      sha256 = "sha256-xCXKbHXb4KH90zfoF+XgSzCAYUs2HFdMBObCpOk3NIc=";
    };
    xf86-video-intel = null; # Latest tag that is not xlibre is from 2014
    xf86-video-mga = rec {
      version = "2.1.0";
      url = "https://github.com/X11Libre/xf86-video-mga/archive/refs/tags/xf86-video-mga-${version}.tar.gz";
      sha256 = "sha256-hXZMtg3IkY52DBVjC8iU1Ovmp4KXojKnUDquFRJpx2M=";
    };
    xf86-video-nouveau = rec {
      version = "1.0.18";
      url = "https://github.com/X11Libre/xf86-video-nouveau/archive/refs/tags/xf86-video-nouveau-${version}.tar.gz";
      sha256 = "sha256-YEDjS7JM8gQRqjGL7EsBaFrdALUk+/ZmkTLf3xsMa0s=";
    };
    xf86-video-nv = rec {
      version = "2.1.23";
      url = "https://github.com/X11Libre/xf86-video-nv/archive/refs/tags/xf86-video-nv-${version}.tar.gz";
      sha256 = "sha256-bAa48eeOCRkHLqD5PSkRRWXpG0qpCS69UeyMyouDniE=";
    };
    xf86-video-qxl = null;
    xf86-video-r128 = rec {
      version = "6.13.0";
      url = "https://github.com/X11Libre/xf86-video-r128/archive/refs/tags/xf86-video-r128-${version}.tar.gz";
      sha256 = "sha256-aoyM8O8BUybpf2B3woKXMa6+lXc2VoVtJOAKr3/9ZIQ=";
    };
    # This failed to build against xlibre-xserver
    xf86-video-siliconmotion = rec {
      version = "1.7.10";
      url = "https://github.com/X11Libre/xf86-video-siliconmotion/archive/refs/tags/xf86-video-siliconmotion-${version}.tar.gz";
      sha256 = "sha256-qvfH+F/pJ5ufJDc8/9GQg56GZunLmYfIxV0/FxCWiBU=";
    };
    xf86-video-vesa = rec {
      version = "2.6.0";
      url = "https://github.com/X11Libre/xf86-video-vesa/archive/refs/tags/xf86-video-vesa-${version}.tar.gz";
      sha256 = "sha256-VQF3I00BptmjjBnnDhZX5DO1v3bZ6XDOnHML9myXsak=";
    };
    xf86-video-vmware = rec {
      version = "13.4.0";
      url = "https://github.com/X11Libre/xf86-video-vmware/archive/refs/tags/xf86-video-vmware-${version}.tar.gz";
      sha256 = "sha256-vYut4MiKSBJEdABnkCwTbU/HbG/J3VmdQWpm+lspUuQ=";
    };
  };
}

